#!/usr/bin/env python3
"""
OSS Licenses 자동 정리 스크립트

사용법:
1. dart run dart_pubspec_licenses:generate 실행
2. python3 tools/clean_oss_licenses.py 실행
3. 정리된 파일 생성 완료!
"""

import re
import sys

def clean_oss_licenses(input_file='lib/oss_licenses.dart', output_file='lib/oss_licenses.dart'):
    """
    oss_licenses.dart 파일을 정리:
    1. allDependencies 섹션 삭제
    2. _devkit_flutter 패키지 정의 삭제
    3. thisPackage 상수 삭제
    4. PackageRef 클래스 삭제
    """

    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()

        print(f"✅ 파일 읽기 완료: {input_file}")
        original_lines = content.count('\n')

        # 1. allDependencies 전체 섹션 삭제
        # 패턴: "/// All dependencies..." 부터 다음 "///" 주석 전까지
        content = re.sub(
            r'/// All dependencies including transitive dependencies\..*?(?=///|\Z)',
            '',
            content,
            flags=re.DOTALL
        )
        print("✅ allDependencies 섹션 삭제 완료")

        # 2. _devkit_flutter 패키지 정의 삭제
        # 패턴: "/// devkit_flutter..." 부터 "); 까지
        content = re.sub(
            r'/// devkit_flutter.*?const _devkit_flutter = Package\(.*?\);',
            '',
            content,
            flags=re.DOTALL
        )
        print("✅ _devkit_flutter 패키지 정의 삭제 완료")

        # 3. thisPackage 상수 삭제
        content = re.sub(
            r'/// This package\..*?const thisPackage = _devkit_flutter;',
            '',
            content,
            flags=re.DOTALL
        )
        print("✅ thisPackage 상수 삭제 완료")

        # 4. PackageRef 클래스 삭제
        content = re.sub(
            r'class PackageRef \{.*?\}',
            '',
            content,
            flags=re.DOTALL
        )
        print("✅ PackageRef 클래스 삭제 완료")

        # 5. Package 클래스에서 dependencies, devDependencies 필드만 제거
        # 주의: Package 클래스 자체는 유지!
        content = re.sub(
            r'  /// Direct dependencies\n  final List<PackageRef> dependencies;\n',
            '',
            content,
            count=1
        )
        content = re.sub(
            r'  /// Direct devDependencies\n  final List<PackageRef> devDependencies;\n',
            '',
            content,
            count=1
        )
        content = re.sub(
            r'    required this\.dependencies,\n',
            '',
            content,
            count=1
        )
        content = re.sub(
            r'    required this\.devDependencies,\n',
            '',
            content,
            count=1
        )
        print("✅ Package 클래스에서 불필요한 필드만 제거 완료 (클래스는 유지)")

        # 7. 각 패키지 정의에서 dependencies, devDependencies 필드 제거
        # 패턴: dependencies: [...], 또는 devDependencies: [...],
        content = re.sub(
            r'    dependencies: \[.*?\],\n',
            '',
            content,
            flags=re.DOTALL
        )
        content = re.sub(
            r'    devDependencies: \[.*?\],\n',
            '',
            content,
            flags=re.DOTALL
        )
        print("✅ 패키지 정의에서 dependencies/devDependencies 필드 제거 완료")

        # 8. dependencies/devDependencies 리스트에서 SDK 기본 패키지 제거
        # Flutter SDK 기본 패키지들
        sdk_packages = [
            '_flutter',
            '_flutter_test',
            '_flutter_web_plugins',
            '_sky_engine',
        ]

        for pkg in sdk_packages:
            # dependencies 리스트에서 제거
            content = re.sub(
                rf'  {pkg},\n',
                '',
                content
            )
            # devDependencies 리스트에서도 제거
            content = re.sub(
                rf'  {pkg},\n',
                '',
                content
            )
        print("✅ SDK 기본 패키지 제거 완료 (_flutter, _flutter_test 등)")

        # 9. 자동 생성 주석 수정 (간결하게)
        content = re.sub(
            r'// This code was generated by dart_pubspec_licenses\n// https://pub\.dev/packages/dart_pubspec_licenses',
            '// Generated by dart_pubspec_licenses, cleaned by tools/clean_oss_licenses.py',
            content
        )
        print("✅ 주석 섹션 업데이트 완료")

        # 10. 죽은 코드 제거 (dependencies/devDependencies에 없는 패키지 정의)

        # dependencies/devDependencies 리스트에서 사용 중인 패키지명 추출
        deps_match = re.search(r'const dependencies = <Package>\[(.*?)\];', content, re.DOTALL)
        devdeps_match = re.search(r'const devDependencies = <Package>\[(.*?)\];', content, re.DOTALL)

        used_packages = set()
        if deps_match:
            used_packages.update(re.findall(r'_\w+', deps_match.group(1)))
        if devdeps_match:
            used_packages.update(re.findall(r'_\w+', devdeps_match.group(1)))

        print(f"✅ 사용 중인 패키지: {len(used_packages)}개")

        # 각 패키지 정의 찾기
        # 패턴: /// 주석(여러 줄 가능) + const _패키지명 = Package( ... );
        # Package( 부터 );까지 찾되, 중첩된 괄호도 고려
        removed_count = 0

        # 모든 const _패키지명 = Package 시작점 찾기
        matches = list(re.finditer(r'(/// [^\n]*\n)+(const (_\w+) = Package\()', content))

        # 역순으로 처리 (인덱스 변경 방지)
        for match in reversed(matches):
            pkg_name = match.group(3)

            if pkg_name not in used_packages:
                start = match.start()

                # Package( 부터 매칭되는 ); 찾기
                depth = 1
                i = match.end()
                while i < len(content) and depth > 0:
                    if content[i] == '(':
                        depth += 1
                    elif content[i] == ')':
                        depth -= 1
                    i += 1

                # ); 뒤의 줄바꿈까지 포함
                if i < len(content) and content[i] == ';':
                    i += 1
                if i < len(content) and content[i] == '\n':
                    i += 1

                end = i

                # 해당 부분 제거
                content = content[:start] + content[end:]
                removed_count += 1

        print(f"✅ 죽은 코드 제거 완료 ({removed_count}개 패키지 정의)")

        # 11. 빈 줄 정리 - 연속된 빈 줄을 1줄로
        content = re.sub(r'\n{3,}', '\n\n', content)
        print("✅ 빈 줄 정리 완료 (연속된 빈 줄 → 1줄)")

        # 결과 저장
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(content)

        cleaned_lines = content.count('\n')
        removed_lines = original_lines - cleaned_lines

        print(f"\n🎉 정리 완료!")
        print(f"📊 통계:")
        print(f"   - 원본 줄 수: {original_lines:,}")
        print(f"   - 정리 후 줄 수: {cleaned_lines:,}")
        print(f"   - 제거된 줄 수: {removed_lines:,}")
        print(f"   - 저장 위치: {output_file}")

        return True

    except FileNotFoundError:
        print(f"❌ 오류: 파일을 찾을 수 없습니다 - {input_file}")
        print(f"💡 먼저 'dart run dart_pubspec_licenses:generate'를 실행하세요!")
        return False
    except Exception as e:
        print(f"❌ 오류 발생: {e}")
        return False


def show_usage():
    """사용법 안내"""
    print("""
🔧 OSS Licenses 자동 정리 도구

사용 방법:
---------
1. 패키지 추가 후 pubspec.yaml 저장
2. 터미널에서 실행:

   flutter pub get
   dart run dart_pubspec_licenses:generate
   python3 tools/clean_oss_licenses.py

3. 완료! lib/oss_licenses.dart가 자동 정리됩니다.

옵션:
-----
python3 tools/clean_oss_licenses.py [입력파일] [출력파일]

예시:
python3 tools/clean_oss_licenses.py lib/oss_licenses.dart lib/oss_licenses.dart
python3 tools/clean_oss_licenses.py input.dart output.dart
""")


if __name__ == '__main__':
    print("=" * 60)
    print("🧹 OSS Licenses 자동 정리 시작")
    print("=" * 60)
    print()

    # 명령줄 인자 처리
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help', 'help']:
        show_usage()
        sys.exit(0)

    input_file = sys.argv[1] if len(sys.argv) > 1 else 'lib/oss_licenses.dart'
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file

    success = clean_oss_licenses(input_file, output_file)

    if success:
        print("\n✨ 모든 작업이 완료되었습니다!")
        sys.exit(0)
    else:
        print("\n💥 작업 실패")
        sys.exit(1)